apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-cert
  namespace: airflow
spec:
  secretName: airflow-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: airflow.redpillhq.com  # Replace with your domain
  dnsNames:
  - airflow.redpillhq.com            # Replace with your domain
